RegMember/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib import admin
from . import views

#url for app
app_name = "RegMember"
urlpatterns = [
    url("RegMember/", views.RegMember, name = "Registration Mamber" ),
    url("saveData/", views.DataMember, name="DataRegistration"),
    url("Thanks/", views.Thankyou, name="Thank You") 
]

TP1/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views as auth_views

from django.contrib.auth import views
from . import views

app_name = "TP1"
urlpatterns = [
	url(r'^$', views.display_TP1, name='/'),
	url(r'^admin/', admin.site.urls),
     url(r'^login/$', auth_views.LoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'^auth/', include('social_django.urls', namespace='social')),
]

TugasPemprograman/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import TP1.urls as TP1
import News.urls as News
import Event.urls as Event
import RegParticipant.urls as RegParticipant
import RegMember.urls as RegMember
import About.urls as About

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include(TP1,namespace='TP1')),
    url(r'^News/', include(News,namespace='News')),
    url(r'^Event/', include(Event,namespace='Event')),
    url(r'^RegParticipant/', include(RegParticipant,namespace='RegParticipant')),
    url(r'', include(RegMember,namespace='Registration Member')),
    url(r'^About/', include(About,namespace='About')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
]  

RegMember/models.py
from django.db import models


class registration_member(models.Model):
    full_name = models.CharField (max_length = 100)
    username = models.CharField(max_length = 70)
    email = models.EmailField(max_length = 100)
    date_birth = models.DateTimeField(max_length = 20)
    password = models.CharField(max_length = 70)
    home_address = models.CharField(max_length = 300)

RegMember/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User

class Form_Registration_Member(forms.Form):

    full_name = {
        'type' : 'text',
        'class' : 'form-control',
        'placeholder' : 'Full Name',
        'cols': 50,
        'rows': 4,
        'id' :'id_full_name'
    }

    username = {
        'type' : 'text',
        'class' : 'form-control',
        'placeholder' : 'Username',
        'cols': 50,
        'rows': 4,
        'id' :'id_username'
    }

    email = {
        'class' : 'form-control',
        'placeholder' : 'E-mail',
        'cols': 50,
        'rows': 4,
        'id' :'id_email'
    }

    date_birth = {
       'type' : 'date',
       'class' : 'form-control',
        'placeholder' : 'Date Birth',
        'cols': 50,
        'rows': 4,
        'id' :'id_date_birth'
    }

    password = {
        'class' : 'form-control',
        'placeholder' : 'Password',
        'cols': 50,
        'rows': 4,
        'id' :'id_password'
    }

    home_address = {
        'type' : 'text',
        'class' : 'form-control',
        'placeholder' : 'Home Address',
        'cols': 50,
        'rows': 4,
        'id' :'id_home_address'
    }


    full_name = forms.CharField (max_length = 100, label = "Full Name ", widget = forms.TextInput(attrs = full_name))
    username = forms.CharField(max_length = 70, label = "User Name ", widget = forms.TextInput(attrs = username))
    email = forms.EmailField(max_length = 100, label = "E-mail ", widget= forms.EmailInput(attrs = email))
    date_birth = forms.DateField(label = "Date Birth ", input_formats= ['%Y-%m-%d'], widget = forms.DateInput(date_birth))
    password = forms.CharField(max_length = 70, min_length = 8, label = "Pasword ", widget=forms.PasswordInput(password))
    home_address = forms.CharField(max_length = 300, label = "Home Address ", widget = forms.TextInput(attrs = home_address))

RegMember/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .models import registration_member
from .forms import Form_Registration_Member


# Fungsi-Fungsi di views 
regis_member = {}

def RegMember(request):
    regis_member['author'] = "Karina Ivana"
    regis_member['data_Member'] = registration_member.objects.all().order_by('-id')
    regis_member['form_Member'] = Form_Registration_Member
    return render(request, 'RegMember.html', regis_member)

def DataMember(request):
    
    registrationMember = Form_Registration_Member(request.POST or None)
    if (request.method == 'POST' and registrationMember.is_valid()):
        print('valid')
        regis_member['full_name'] = request.POST['full_name']
        regis_member['username'] = request.POST['username']
        regis_member['email'] = request.POST['email']
        regis_member['date_birth'] = request.POST['date_birth']
        regis_member['password'] = request.POST['password']
        regis_member['home_address'] = request.POST['home_address']
        daftarMember =registration_member(full_name = regis_member['full_name'], username = regis_member['username'], 
                        email = regis_member['email'], date_birth = regis_member['date_birth'], password = regis_member['password'], 
                        home_address = regis_member['home_address'])
        daftarMember.save()
        regis_member['data_Member'] = registration_member.objects.all()
        return HttpResponseRedirect('/Thanks/')
    else :
        return HttpResponseRedirect('/RegMember/')

def Thankyou(request):
    response = {}
    return render(request, 'Thankyou.html', response)

RegMember/templates/RegMember.html
{% load staticfiles %}
{% load static %}

<body id="backgroundRegMember">
    {% include 'navbar.html' %}


    <section>
        <div class= "container-fluid">
            <h1 class="text-center"> Formulir Registration Member </h1>
            <div class="row">
                <div class="col-sm-9">
                        <form id = 'form' method="POST" action="{% url 'RegMember:DataRegistration' %}">
                            {% csrf_token %}
                            {{ form_Member.as_p }}

                            <button type="submit" class="btn btn-default">Submit</button>
                        </form>
                </div>

                <div class="col-sm-2">
                    <table class="table">
                        <thead>
                            <th>Full Name</th>
                        </head>
                            {% for i in data_Member %}
                            <tr>
                                <td> {{i.full_name}} </td>
                            </tr>
                            {% endfor %}
                    </table>
                </div>
            </div>
            <br>
            <br>
        </div>
    </section>
</body>
</html>

RegMember/templates/Thankyou.html
{% load staticfiles %}
{% load static %}

<body>

    {% include 'navbar.html' %}
    <section>
        <div class= "container-fluid text-center" id="backgroundThanks">
            <div class="textThankYou">
            <h1 > Thank You</h1>
            <h2 > Thanks for your participation in our website </h2>
            <br>
            <a class="btn btn-secondary btn-lg" role="button" id = "buttonThanks" href="/">Home</a>
        </div>
        </div>
    </section>
</body>
</html> 

RegMember/templates/navbar.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Registation Member</title>
        <link rel="shortcut icon" type="image/png" href="https://i.imgur.com/zQbyEia.png"/>
        <link rel = "stylesheet" href="{% static 'RegistrationMember.css' %}" type="text/css">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    
        {% block link %} {%endblock%}

      </head>

    <body>
            <nav class="navbar transparent navbar-expand-lg navbar-dark" style="background-color: black;">
                    <a class="navbar-brand" href="#" style="background-color: white;" ></a>
                      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" style="background-color: black;">
                        <span class="navbar-toggler-icon"></span>
                      </button>
                      <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav" style="text-align: center; ">
                          <li class="nav-item active">
                            <a class="nav-link" href="/">
                            <img style="float: left; " width="60px" height="70px"src="https://i.imgur.com/zQbyEia.png" >
                            </a>
                          </li>
                          <li class="nav-item active">
                            <a style="color:white; padding-top: 1.5vw;font-size: 25px; padding-left: 3vw" class="nav-link" href="/About/">Profile</a>
                          </li>
                          <li class="nav-item">
                                        <a style="color:white; padding-top: 1.5vw;font-size: 25px; " class="nav-link" href="/News/">News</a>
                                    </li>
                                    <li class="nav-item">
                            <a style="color:white;  padding-top: 1.5vw; font-size: 25px" class="nav-link" href="/Event/">Event</a>
                          </li>
                          <li class="nav-item"> <a style="color:white;padding-top: 1.5vw; font-size: 25px; padding-left: 65vw " class="nav-link" href="/RegParticipant/">Join us !</a>
                          </li>
                        </ul>
                      </div>
                    </a>
                    </nav>
            <!--Akhir dari Navbar Registrasi Member-->
    </body>
</html>