About/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views as auth_views

from django.contrib.auth import views
from . import views


app_name = "About"

urlpatterns = [
    url(r"form_testi/", views.form, name='testi'),
    url(r'^login/$', auth_views.LoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'is_login/', views.is_login, name='is_login'),
    url(r'', views.about, name='About'),
]

TP1/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views as auth_views

from django.contrib.auth import views
from . import views

app_name = "TP1"
urlpatterns = [
	url(r'^$', views.display_TP1, name='/'),
	url(r'^admin/', admin.site.urls),
     url(r'^login/$', auth_views.LoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'^auth/', include('social_django.urls', namespace='social')),
]

TugasPemprograman/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import TP1.urls as TP1
import News.urls as News
import Event.urls as Event
import RegParticipant.urls as RegParticipant
import RegMember.urls as RegMember
import About.urls as About

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include(TP1,namespace='TP1')),
    url(r'^News/', include(News,namespace='News')),
    url(r'^Event/', include(Event,namespace='Event')),
    url(r'^RegParticipant/', include(RegParticipant,namespace='RegParticipant')),
    url(r'', include(RegMember,namespace='Registration Member')),
    url(r'^About/', include(About,namespace='About')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
]  

About/models.py
from django.db import models


class Testimoni(models.Model):
    Comment = models.TextField(max_length=1000)
    

About/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.db import models
from .models import Testimoni

class Form_Testimoni(forms.Form):
  Comment = forms.CharField(widget=forms.Textarea(attrs={
  'id'    : 'post-text',
  'class'   : 'form-control',
  'required'  : True,
  'placeholder' : 'Write your testimonial here......',
 }), label='', max_length=5000)
 
   

About/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.http import HttpResponse, JsonResponse
from .models import Testimoni
from .forms import Form_Testimoni
import json


response ={}

def about(request):
	komen = Testimoni.objects.all().order_by('-id')
	response['komen'] = komen
	response['formtesti'] = Form_Testimoni
	html = 'about.html'
	form = Form_Testimoni(request.POST or None)
	
	if (request.method == 'POST'):
		response['Comment'] = request.POST['Comment']
		
		
		save_data = Testimoni(Comment = response['Comment'])
		save_data.save()
		save_data = Testimoni.objects.all().order_by('-id')
		return render(request, html, response)
	return render(request, html, response)

def form(request):
	response = {}
	if not request.user.is_authenticated:
		return HttpResponseRedirect("/About/")
		
	response["formtesti"] = Form_Testimoni
	return render(request, 'commentforms.html', response)


def is_login(request):
	print("is_login")
	if  request.user.is_authenticated and "form" in request.session:
		print("is_authenticated")
		if len(request.session["form"]) == 0:
			return JsonResponse({
				'event': "You have'nt registered for any events yet",
				'status':'success'
			})
		else:
			return JsonResponse({
				'event': request.session["form"],
				'status':'success'
			})

	elif request.user.is_authenticated and "form" not in request.session:
		request.session["form"]=[]
		return JsonResponse({
			'event': "You have'nt registered for any events yet",
			'status':'success'
		})

	else:
		print("Not_authenticated")
		return JsonResponse({
			'event': "-",
			'status':'fail'
		})

About/templates/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<!-- ###################################################################################################################################################################        -->
<head>
    <title>About Neavent</title>
    <meta charset="UTF-8">
    <link rel="shortcut icon" type="image/png" href="https://i.imgur.com/zQbyEia.png"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <script src="{% static 'js/script.js' %}"></script>
    <style type="text/css">
		body{
            background-color:  #ccb3ff;
            background-image: url("https://i.imgur.com/3A5fKrS.jpg")
			/* background: linear-gradient(to right, #809fff, #d966ff);  */
        }
        
		#myInput{
			background-image: url('https://img.icons8.com/cotton/50/000000/search.png');
		  	background-position: right;
		  	background-repeat: no-repeat;
		  	width: 30%;
		  	font-size: 16px;
		  	padding: 12px 20px 12px 40px;
		  	border: 1px solid #ddd;
		  	margin-bottom: 12px;
        }
    
        @media (min-width: 576px){

        .jumbotron {
            padding: 10rem 10rem;
            margin-bottom: 2rem; 
            /* background-image: linear-gradient( 135deg, #9f05ffb6 10%, #fd5e089a 100%); */
            /* background-color: rgb(4, 35, 65); */
            background-color: rgba(214, 23, 221, 0.4);
            border-radius: 3rem;
            height: 500px;
        }

        div {
            display: block;
        }

        .ml1 {
            font-weight: 900;
            font-size: 7em;
            text-align: center;
            align-content: center;
            align-items: center;
            color: #fff;
            font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
            
        }

        .ml1 .letter {
            display: inline-block;
            line-height: 1em;
        }

        .ml1 .text-wrapper {
            position: relative;
            display: inline-block;
            padding-top: 0.1em;
            padding-right: 0.05em;
            padding-bottom: 0.15em;
        }

        .ml1 .line {
            opacity: 0;
            position: absolute;
            left: 0;
            height: 3px;
            width: 100%;
            background-color: #fff;
            transform-origin: 0 0;
        }

        .ml1 .line1 { 
            top: 0; 
        }

        .ml1 .line2 { 
            bottom: 0; 
        
        }
    }

    </style>
</head>
<!-- ###################################################################################################################################################################        -->

<!-- ###################################################################################################################################################################        -->
<body >
    <!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
    <!-- Navigation Bar -->
    <nav class="navbar transparent navbar-expand-lg navbar-dark" style="background-color: black;">
		<a class="navbar-brand" href="#" style="background-color: white;" ></a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" style="background-color: black;">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNav">
				<ul class="navbar-nav" style="text-align: center; ">
					<li class="nav-item active">
						<a class="nav-link" href="/">
						<img style="float: left; " width="60px" height="70px"src="https://i.imgur.com/zQbyEia.png" >
						</a>
					</li>
					<li class="nav-item active">
						<a style="color:white; padding-top: 1.5vw;font-size: 25px; padding-left: 3vw" class="nav-link" href="/About/">Profile</a>
					</li>
					<li class="nav-item">
                        <a style="color:white; padding-top: 1.5vw;font-size: 25px; " class="nav-link" href="/News/">News</a>
                    </li>
                    <li class="nav-item">
						<a style="color:white;  padding-top: 1.5vw; font-size: 25px" class="nav-link" href="/Event/">Event</a>
					</li>
					<li class="nav-item">
                        {% if user.is_authenticated %}
                        <a style="color:white;padding-top: 1.5vw; font-size: 25px; padding-left: 60vw " class="nav-link" href="{% url 'TP1:logout' %} ">Logout</a>
                        {% else %} 
                        <a style="color:white;padding-top: 1.5vw; font-size: 25px; padding-left: 60vw " class="nav-link" href="{% url 'social:begin' 'google-oauth2' %} ">Login</a>
                    </li>
                    {% endif %}
				</ul>
			</div>
		</a>
    </nav>
    <!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
    
    <!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
    <!-- Tulisan bergerak dan pengaturan jumbotron -->
    {% csrf_token %}
    <main role="main">
        <div class="jumbotron" >
            <div class="container">
                <h1 class="ml1">
                    <span class="text-wrapper">
                    <span class="line line1"></span>
                    <span class="letters">NEAVENT</span>
                    <span class="line line2"></span>
                    </span>
                    <br>
                    <span class='letters' style="font-size: 20px;text-align: center;">“Your News and Event won’t Escape our Blackhole”</span>
                    
                </h1>
            </div>
        </div>  
    </main>
    <!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->

    <!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
    <!-- Penjelasan tentang About Company Profile -->
    <div style="background-color:rgba(255, 255, 255, 0.7); padding-left: 2%; padding-right: 2%;border-radius: 3rem">
        <br>    
        <h1 style="text-align:center; font-size: 50px; "><strong>COMPANY PROFILE</strong></h1>
        <br>
        <center>
            <img style="align-content: center;align-items: center;width: 400px"    src="https://i.imgur.com/zQbyEia.png" alt="Logo Neavent"  class="center">
        </center>
        <p style="font-size: 24px; text-align: center;">
            Neavent merupakan sebuah website yang mewadahi mahasiswa untuk berorganisasi dan berkreasi.
            Platform ini menyajikan sebuah News dan Event yang diselenggarakan oleh kampus, serta mahasiswa 
            dapat mendaftarkan diri sebagai member dari Neavent dan juga mendaftarkan ke suatu event yang akan diselenggarakan. 
        </p>
        <br>
    </div>
    <br><br>
    <!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
    
    <!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
    <!-- Button Add New Testimoni buat yang Login -->
    <center>
        <form action="About/form_testi/">
                <input id="ilang"  class="inputForm"  style="width: 180px; height: 60px;background: white;border: black 10px" type="submit" value="Add New Testimoni">
        </form>
    </center>
    <br>
    <br>
    <!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
    
    <!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
    <!-- Tabel nampilin testimoni -->
    <div  style="background-color:rgba(255, 255, 255, 0.7);padding-left: 2%; padding-right: 2%; border-radius: 3rem;">
        <div class="front">
            <br>
            <br>
            <h1 style="text-align:center;" ><strong>WHAT THEY THINK ABOUT US</strong></h1>
            
            <div>
                {% for i in komen  %}
            
                <div style="margin: 5%;background-color: whitesmoke;padding-top: 3%;padding-bottom: 3%;padding-left: 2%;text-align: center">{{i.Comment}}</div>
                {% endfor %}
            </div>
            <br>
            <br>
        </div>
    </div>
    <br>
    <br>
    <!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-->
</body>
<!-- ###################################################################################################################################################################        -->

<!-- ###################################################################################################################################################################        -->
<!-- Footer -->
<footer class="footer" style="background-color:transparent;align-content: center;align-items: center">
    <center>
        <a href="#" class="w3-button w3-light-grey"><i class="fa fa-arrow-up w3-margin-right"></i>To the top</a>
        <br>
        <br>
    </center>
    
</footer>
<!-- ###################################################################################################################################################################        -->

</html>

About/templates/commentforms.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<!-- ###################################################################################################################################################################        -->
<head>
    <title>Form Testimoni Neavent</title>
    <meta charset="UTF-8">
    <link rel="shortcut icon" type="image/png" href="https://i.imgur.com/zQbyEia.png"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <script src="{% static 'js/script.js' %}"></script>
    <style type="text/css">
		body{
			/* background: linear-gradient(to right, #809fff, #d966ff);  */
            background-image: url("https://vignette.wikia.nocookie.net/animal-jam-clans-1/images/c/ca/Galaxy-0.jpg/revision/latest?cb=20160425215139");
        }
        
		#myInput{
			background-image: url('https://img.icons8.com/cotton/50/000000/search.png');
		  	background-position: right;
		  	background-repeat: no-repeat;
		  	width: 30%;
		  	font-size: 16px;
		  	padding: 12px 20px 12px 40px;
		  	border: 1px solid #ddd;
		  	margin-bottom: 12px;
        }
    

    </style>
</head>
<!-- ###################################################################################################################################################################        -->

<body>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: black;">
		<a class="navbar-brand" href="#" style="background-color: white;" ></a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" style="background-color: black;">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarNav">
				<ul class="navbar-nav" style="text-align: center; ">
					<li class="nav-item active">
						<a class="nav-link" href="/">
						<img style="float: left; " width="60px" height="70px"src="https://i.imgur.com/zQbyEia.png" >
						</a>
					</li>
					<li class="nav-item active">
						<a style="color:white; padding-top: 1.5vw;font-size: 25px; padding-left: 3vw" class="nav-link" href="/About/">Profile</a>
					</li>
					<li class="nav-item">
                        <a style="color:white; padding-top: 1.5vw;font-size: 25px; " class="nav-link" href="/News/">News</a>
                    </li>
                    <li class="nav-item">
						<a style="color:white;  padding-top: 1.5vw; font-size: 25px" class="nav-link" href="/Event/">Event</a>
					</li>
					
				</ul>
			</div>
		</a>
	</nav>

    <div style="background-color:rgba(255, 255, 255, 0.8); padding-left: 2%;padding-right: 2% ; align-content: center;align-items: center">
    <br>

    <div class="front">
        <h1 style="text-align:center; "><strong>Form Testimoni</strong></h1>
            <div>
                <br>
            </div>
            <section class = "result">
            
            <form id = "" method="POST" action="{% url 'About:About' %}">
                {% csrf_token %}
                {{formtesti.as_p}}
                <div>
                    <strong><label class = "text">{{field.label}}</label></strong>{{field}}
                </div>
                <center>
                <div class = "submit-btn" style="align-items: center">
                    <input type = "submit" value="Submit">
                    <br>
                    <br>
                </div>
            </center>
            </form>
        </div>
    </div>
    <br>
    <br>
    <br>


</body>
</html>