RegParticipant/urls.py
from django.conf.urls import url
from . import views

app_name = "RegParticipant"
urlpatterns = [
	url('', views.partisipan, name='RegParticipant_event'),
]

TP1/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views as auth_views

from django.contrib.auth import views
from . import views

app_name = "TP1"
urlpatterns = [
	url(r'^$', views.display_TP1, name='/'),
	url(r'^admin/', admin.site.urls),
     url(r'^login/$', auth_views.LoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'^auth/', include('social_django.urls', namespace='social')),
]

TugasPemprograman/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import TP1.urls as TP1
import News.urls as News
import Event.urls as Event
import RegParticipant.urls as RegParticipant
import RegMember.urls as RegMember
import About.urls as About

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include(TP1,namespace='TP1')),
    url(r'^News/', include(News,namespace='News')),
    url(r'^Event/', include(Event,namespace='Event')),
    url(r'^RegParticipant/', include(RegParticipant,namespace='RegParticipant')),
    url(r'', include(RegMember,namespace='Registration Member')),
    url(r'^About/', include(About,namespace='About')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
]  

RegParticipant/models.py
from django.db import models

class Peserta(models.Model):
    event = models.CharField(max_length=300)
    detail = models.CharField(max_length=3000)
    username = models.CharField(max_length=300)
    email = models.CharField(max_length=300)


class Peserta_detail(models.Model):
    username = models.CharField(max_length=300)
    email = models.CharField(max_length=350)
    daftar_event = models.CharField(max_length=30000)

RegParticipant/forms.py
from django.db import models
from django import forms
from .models import Peserta, Peserta_detail

class Peserta_Form(forms.Form):
    Event = (
        ('LEARN SAP BW ON HANA SELF PACED TRAINING-SAP BW', 'LEARN SAP BW ON HANA SELF PACED TRAINING-SAP BW'),
        ('THE 26TH INDOCOMTECH 2018', 'THE 26TH INDOCOMTECH 2018'),
        ('CLASSIC HALLOWEEN NIGHT WITH NAIF', 'CLASSIC HALLOWEEN NIGHT WITH NAIF'),
        ('RCTI REDS RUN 2018',  'RCTI REDS RUN 2018'),
    ) 
    event = forms.CharField(label = 'Event',required = True, max_length = 300,widget = forms.Select(choices = Event))

RegParticipant/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate
from django.contrib import messages
import TP1
from .models import Peserta_detail, Peserta
from .forms import Peserta_Form


response ={}
def partisipan(request):
	if request.user.is_authenticated:
		usernames = Peserta.objects.all().order_by('-id')
		response['usernames'] = usernames
		response['formpeserta'] = Peserta_Form
		html = 'RegParticipant.html'
		
		# print(request.session["daftar_event"])
		# print(request.session["email"])

		if (request.method == 'POST'):
			response['event'] = request.POST['event']
			text = request.session["daftar_event"]
			text.append(response['event'])
			request.session['daftar_event'] = text

			print(request.session["daftar_event"])

			usernameUser = request.session["username"]
			save_peserta = Peserta(event = response['event'], detail = request.session['daftar_event'], username = usernameUser, email = request.session['email'])
			save_peserta.save()
		return render(request, html, response)
	else:
		return HttpResponseRedirect('/')

RegParticipant/templates/RegParticipant.html
{% load staticfiles %}
{% load static %}

<body>
		{% include 'navbar_Participant.html' %}
	<div class="container" >
		
		<div>
			<br>
		</div>

		<div class="row">
			<!-- COLUMN UNTUK ISI INPUTAN FORM -->
			<div class="col-sm-8" style="background-color: white; opacity: 0.7; ">
			<br>
			<div class="front">
				<h1 style="text-align:center; bold"><strong>Event Registration</strong></h1>
					<div>
						<br>
					</div>
					<section class = "result">
					
					<form id = "form_participant" method="POST" action="{% url 'RegParticipant:RegParticipant_event' %}">
						{% csrf_token %}
						{{formpeserta.as_p}}
						<div>
							<strong><label class = "text">{{field.label}}</label></strong>{{field}}
						</div>
						<div class = "submit-btn" style="align-items: center">
							<input type = "submit" value="Submit">
							<br>
							<br>
						</div>
					</form>
				</div>
			</div>

			<!-- COLUMN UNTUK MENAMPILKAN DAFTAR PESERTA YANG SUDAH TERDAFTAR -->
			<div class="col-sm-4" style="background-color: whitesmoke; opacity: 0.7;">
				<div class="front">
					<table class = "table table-striped table-dark" style="margin: 1%">
						<div>
							<br>
						</div>	
						<thead>
							<th style="text-align:center">List of Participant</th>
							<th style="text-align:center">Name of Event</th>
						</thead>
						<tbody>
							{% for i in usernames %}
							<tr>
								<td>{{i.username}}</td>
								<td>{{i.event}}</td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
	<script>
    function myFunction() {
      alert("Hello! I am an alert box!");
    }
    </script>
		</div>
	</div> 
	
</body>
</html>
            

RegParticipant/templates/navbar_Participant.html
{% load staticfiles %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<title>RegParticipant</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static 'css/RegParticipant.css' %}" type="text/css">
	<script src="{% static 'js/RegParticipant.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	
</head>

<body background=https://i.imgur.com/fVK4MVE.png>
	<!-- NAVIGATION BAR -->
    <nav class="navbar transparent navbar-expand-lg navbar-dark" style="background-color: black;">
			<a class="navbar-brand" href="#" style="background-color: white;" ></a>
			  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" style="background-color: black;">
				<span class="navbar-toggler-icon"></span>
			  </button>
			  <div class="collapse navbar-collapse" id="navbarNav">
				<ul class="navbar-nav" style="text-align: center; ">
				  <li class="nav-item active">
					<a class="nav-link" href="/">
					<img style="float: left; " width="60px" height="70px"src="https://i.imgur.com/zQbyEia.png" >
					</a>
				  </li>
				  <li class="nav-item active">
					<a style="color:white; padding-top: 1.5vw;font-size: 25px; padding-left: 3vw" class="nav-link" href="/About/">Profile</a>
				  </li>
				  <li class="nav-item">
								<a style="color:white; padding-top: 1.5vw;font-size: 25px; " class="nav-link" href="/News/">News</a>
							</li>
							<li class="nav-item">
					<a style="color:white;  padding-top: 1.5vw; font-size: 25px" class="nav-link" href="/Event/">Event</a>
				  </li>
				  <li class="nav-item"> <a style="color:white;padding-top: 1.5vw; font-size: 25px; padding-left: 65vw " class="nav-link" href="/RegParticipant/">Join us !</a>
				  </li>
				</ul>
			  </div>
			</a>
			</nav>
</body>
</html>